version: '3'

services: 

  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: bribeiro/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "1234:443"
    networks:
      - test-network
    depends_on:
      - "node1"
      - "node2"
      - "node3"

  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - test-network

  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    container_name: alura-books-1
    ports:
      - "3000"
    networks:
      - test-network
    depends_on:
      - mongodb

  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    container_name: alura-books-2
    ports:
      - "3000"
      - "3000"
    networks:
      - test-network
    depends_on:
      - mongodb

  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    container_name: alura-books-3
    ports:
      - "3000"
    networks:
      - test-network
    depends_on:
      - mongodb

networks:
  test-network:
    driver: bridge